name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - name: Crystal Ameba Linter
      uses: crystal-ameba/github-action@v0.8.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Build
      run: crystal build ./src/raytin1w.cr --debug --error-trace
