name: Crystal CI

permissions:
  contents: write
  pull-requests: write

on:
  push:
    paths:
      - "src/**"
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Lint:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: shards install
      - name: Ameba Linter
        run: ./bin/ameba

  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: crystal build ./src/raytin1w.cr --release --no-debug
      - name: Create image
        run: ./raytin1w > traced.ppm
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: traced-ppm
          path: traced.ppm
